name: Publish

on:
  release:
    types:
      - published

jobs:
  build:
    name: Release build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '5.4'

      - name: Download latest phar-composer.phar
        run: composer run-script download-phar-composer

      - name: Build phar
        run: composer run-script build

      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: rocket.phar
